create database "GestPro"
    with owner postgres;

comment on database "GestPro" is 'Project managment Software';

create sequence public.t_board_board_id_seq;

alter sequence public.t_board_board_id_seq owner to postgres;

create sequence public.t_card_card_id_seq;

alter sequence public.t_card_card_id_seq owner to postgres;

create sequence public.t_labels_label_id_seq;

alter sequence public.t_labels_label_id_seq owner to postgres;

create sequence public.t_list_card_list_card_id_seq;

alter sequence public.t_list_card_list_card_id_seq owner to postgres;

create sequence public.t_users_user_id_seq;

alter sequence public.t_users_user_id_seq owner to postgres;

create sequence public.t_workspace_workspace_id_seq;

alter sequence public.t_workspace_workspace_id_seq owner to postgres;

create sequence public.user_roles_id_seq;

alter sequence public.user_roles_id_seq owner to postgres;

create table public.t_board
(
    id           bigint generated by default as identity
        primary key,
    workspace_id bigint,
    name         varchar(255)
);

alter table public.t_board
    owner to postgres;

alter sequence public.t_board_board_id_seq owned by public.t_board.id;

create table public.t_card
(
    id           bigint generated by default as identity
        primary key,
    list_card_id bigint,
    name         varchar(255),
    description  varchar(255),
    deadline     date
);

alter table public.t_card
    owner to postgres;

alter sequence public.t_card_card_id_seq owned by public.t_card.id;

create table public.t_labels
(
    id    bigint generated by default as identity
        primary key,
    color varchar(255)
);

alter table public.t_labels
    owner to postgres;

alter sequence public.t_labels_label_id_seq owned by public.t_labels.id;

create table public.t_list_card
(
    board_id bigint
        constraint fk_board_id_board
            references public.t_board
            on update cascade on delete cascade,
    id       bigint generated by default as identity
        primary key,
    name     varchar(255)
);

alter table public.t_list_card
    owner to postgres;

alter sequence public.t_list_card_list_card_id_seq owned by public.t_list_card.id;

create table public.t_users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255),
    username varchar(255),
    password varchar(255),
    role_id  varchar(10)
);

alter table public.t_users
    owner to postgres;

alter sequence public.t_users_user_id_seq owned by public.t_users.id;

create table public.t_workspace
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255)
);

alter table public.t_workspace
    owner to postgres;

alter sequence public.t_workspace_workspace_id_seq owned by public.t_workspace.id;

create table public.tj_label_card
(
    label_id integer not null
        constraint fk_label_id
            references public.t_labels,
    card_id  integer not null
        constraint fk_card_id
            references public.t_card,
    primary key (label_id, card_id)
);

alter table public.tj_label_card
    owner to postgres;

create table public.tj_user_workspace
(
    user_id      integer not null
        constraint fk_user_id
            references public.t_users,
    workspace_id integer not null
        constraint fk_workspace_id
            references public.t_workspace,
    primary key (user_id, workspace_id)
);

alter table public.tj_user_workspace
    owner to postgres;

create table public.tj_user_card
(
    user_id integer not null
        constraint fk_user_id_users
            references public.t_users,
    card_id integer not null
        constraint fk_card_id_card
            references public.t_card,
    constraint pk_card_id_user_id
        primary key (card_id, user_id)
);

alter table public.tj_user_card
    owner to postgres;

create table public.t_roles
(
    id   integer generated always as identity
        constraint user_roles_pk
            primary key,
    name varchar(10)
);

alter table public.t_roles
    owner to postgres;

alter sequence public.user_roles_id_seq owned by public.t_roles.id;

create table public.tj_user_roles
(
    user_id integer not null
        constraint tj_user_roles_t_users_id_fk
            references public.t_users,
    role_id integer not null
        constraint tj_user_roles_t_roles_id_fk
            references public.t_roles
);

alter table public.tj_user_roles
    owner to postgres;
