spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false

    application:
        name: gestpro

    datasource:
        url: jdbc:postgresql://localhost:5432/gestpro
        username: postgres
        password: gestpro123
        driver-class-name: org.postgresql.Driver

    jpa:

        show-sql: true
        properties:
            hibernate:
                format_sql: true

    profiles:
        active: dev

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com

            client:
                registration:
                    google:
                        client-id: ${GOOGLE_OAUTH_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/google"
                        scope:
                            - profile
                            - email

                    github:
                        client-id: Ov23liGBc9wuOQ9SDN8a
                        client-secret: b242648ddd497b44720a04436e954d5cc6d37e86
                        authorization-grant-type: authorization_code
                        scope:
                            - openid
                            - profile
                        # redirect-uri: http://localhost:4200/callback
                        # client-name: GitHub

                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user
                        user-name-attribute: login

server:
    error:
        whitelabel:
            enabled: false